# Generated by Django 5.1 on 2024-09-03 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Home', 'Home'), ('Personal', 'Personal'), ('Official', 'Official'), ('Business', 'Business')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('NIN', 'NIN'), ('PASSPORT', 'PASSPORT'), ("VOTER'S CARD", "VOTER'S CARD"), ("DRIVER'S LICENSE", "DRIVER'S LICENSE")], max_length=60)),
                ('id_number', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('arrival_from', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('remarks', models.TextField()),
                ('reservation_date', models.DateField(auto_now=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.SmallIntegerField()),
                ('numberOfBeds', models.SmallIntegerField()),
                ('roomType', models.CharField(choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=20)),
                ('price', models.FloatField()),
                ('statusStartDate', models.DateField(null=True)),
                ('statusEndDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('roomPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReservation', models.DateField(default=django.utils.timezone.now)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest')),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Dependees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.booking')),
            ],
        ),
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10, null=True)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(default=django.utils.timezone.now)),
                ('servicesType', models.CharField(choices=[('Food', 'Food'), ('Cleaning', 'Cleaning'), ('Technical', 'Technical')], max_length=20)),
                ('price', models.FloatField()),
                ('curBooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.rooms')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype')),
            ],
        ),
    ]
