# Generated by Django 5.0.3 on 2024-09-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetails',
            name='dob',
        ),
    ]
