# Generated by Django 5.0.3 on 2024-09-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_guestdetails_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
