# Generated by Django 5.1 on 2024-09-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_payment_additionalpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation_det',
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='payment_det',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash payment', 'Cash payment'), ('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer')], max_length=100),
        ),
    ]
