# Generated by Django 5.1 on 2024-09-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_payment_reservation_det_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdetails',
            options={'ordering': ['-reservation_date', '-date_edited']},
        ),
    ]
