# Generated by Django 5.1 on 2024-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
