# Generated by Django 5.1 on 2024-09-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_remove_reservationdetails_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='room_det',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roomdetails'),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms'),
        ),
    ]
