# Generated by Django 5.1 on 2024-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_rooms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
